/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jackie_encodeMedia_FFMpeg */

#ifndef _Included_com_jackie_encodeMedia_FFMpeg
#define _Included_com_jackie_encodeMedia_FFMpeg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jackie_encodeMedia_FFMpeg
 * Method:    videoDecode
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jackie_encodeMedia_FFMpeg_videoDecode
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
