/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jackie_encodeMedia_FFmpeg */

#ifndef _Included_com_jackie_encodeMedia_FFmpeg
#define _Included_com_jackie_encodeMedia_FFmpeg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jackie_encodeMedia_FFmpeg
 * Method:    ffmpegcore
 * Signature: (I[Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jackie_encodeMedia_FFmpeg_ffmpegcore
  (JNIEnv *, jobject, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
