/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jackie_endcodevideo_FFMpeg */

#ifndef _Included_com_jackie_endcodevideo_FFMpeg
#define _Included_com_jackie_endcodevideo_FFMpeg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jackie_endcodevideo_FFMpeg
 * Method:    nFindDecoder
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_jackie_endcodevideo_FFMpeg_nFindDecoder
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
